# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
# '-----------------------------------------------------------------------------------' #
# |                                                                                   | #
# |            _____       __                    ___   __                _            | #
# |           |  __ \     / _|                  | \ \ / /               | |           | #
# |           | |__) |___| |_ ___ _ __ _ __ __ _| |\ V / _ __   ___ _ __| |_          | #
# |           |  _  // _ \  _/ _ \ '__| '__/ _` | | > < | '_ \ / _ \ '__| __|         | #
# |           | | \ \  __/ ||  __/ |  | | | (_| | |/ . \| |_) |  __/ |  | |_          | #
# |           |_|  \_\___|_| \___|_|  |_|  \__,_|_/_/ \_\ .__/ \___|_|  \__|          | #
# |                                                     | |                           | #
# |                                                     |_|                           | #
# |          Thank you for your purchase!  Your support means a lot to me :)          | #
# '-----------------------------------------------------------------------------------' #
#                                                                                       #
#     Developed:                     My profile page:                                   #
#     By SadShrimpy#9190 with <3  -  https://www.spigotmc.org/members/shiry.583821/     #
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

# Do not modify this value, it may CORRUPT the entire config file!
version: v1.0.0-Relase

# Please keep this true <3
bstats: true # todo

############################################################
# +------------------------------------------------------+ #
# |                      Databases                       | #
# +------------------------------------------------------+ #
############################################################

# With databases, the plugin can store information necessary for its operation.
# For example, the total time it took to use a referral code, the number of players invited,
# the number of players who used your code, and, when...

database: #todo SQLite & MySQL
    # By disabling this entry, you will not be able to encapsulate any information
  enabled: true
    # Here you can customize the amount of minutes that will elapse between database synchronizations, on cached game data.
    # In particular, to avoid continuous database operations, the plugin keeps the most frequent, and recently requested, data in the cache.
  sync:
      # Every sync-time minutes the database will be updated via the data kept in the cache, up to that point.
      # It is recommended to enter a number of minutes that varies between 10 and 20 minutes.
    time: 15
      # Perform synchronization in mode: Synchronous or Asynchronous?
      #   -> A-SYNC : the task will be executed concurrently along other tasks;
      #   -> SYNC : the task will be executed on the server's main thread (complex tasks can involve lag and performance issues).
    mode: "A-SYNC"
    # Select the type of database you want to use from:
    #   -> MySQL: client-server, database that manages the entire database, via an external host;
    #   -> SQLite: serverless, file-based database engine that stores the entire database in a single file (~/plugins/ReferralXpert/refXsqlite.db).
  type: "MySQL"
  MySQL:
    hostname: "localhost"
    port: 3306
    database-name: "referralxpert"
    username: "root"
    password: ""
    use-ssl: false
  SQLite:
    encrypt-data:
        # Select whether you want to encrypt all data.
      enabled: true
        # Select the encryption algorithm you most prefer. Those supported are:
        #  -> AES-128
        #  -> DES-56
        #  -> DESede-168
        #  -> HmacSHA1
        #  -> HmacSHA256
      algorithm: "AES-128"
        # # --> IMPORTANT <-- # #
        # For security reasons, the encryption key will have to be placed in the file specified here.
        # This file will AUTOMATICALLY GENERATE A NEW KEY EACH TIME IT IS RECREATED!!
        #  Should you wish to regenerate a key, use the /rxp secret regen-sql-key command.
        #  Alternatively, create a key that respects the parameters of the selected encryption algorithm.
      key-file: "secret-key-sqlite.txt"


############################################################
# +------------------------------------------------------+ #
# |                  Referral Options                    | #
# +------------------------------------------------------+ #
############################################################

# Here you can change all the settings related to the mechanics offered by the plugin.

        # ---------------------------------- #
# # # # #   THE CODES ARE CASE-SENSITIVE !   # # # # #
        # ---------------------------------- #

referral:
    # If true the players with the same ip, can not refer each other.
  ip-check: true
    # Set the maximum number of times a player can redeem ANY code, it is recommended to keep this value at -1 (infinite times).
    # For example if you keep 4, a player can redeem a total of 4 codes. While setting this to -1, a player can redeem as many codes as he wants.
  redeem-per-player: -1
    # Use the playtime to set a MINIMUM PLAYTIME (in minutes) that a player must achieve before being able to redeem any code.
    # Set this to -1 for having no time limit (equal to 0s).
  playtime: 15



# FORSE - idee:
# -----> TRACKING DELLE STATISTICHE DI REFERRAL
#   Tieni traccia delle statistiche di referral per ciascun utente,
#     - codici utilizzati
#     - come il numero di giocatori invitati,
#     - il tempo medio che i giocatori invitati trascorrono sul server,
#     - il numero di giocatori che diventano attivi dopo essere stati invitati,
#   Queste informazioni possono essere utilizzate per migliorare il sistema di referral e premiare gli utenti più efficaci
#

# -----> EVENTI A TEMPO LIMITATO PER I REFERRAL
#   Introduci eventi a tempo limitato in cui i giocatori possono guadagnare premi bonus
#   per ogni referral ottenuto durante quel periodo.
#   Ad esempio, potresti avere un evento "Weekend di inviti" in cui ogni nuovo giocatore
#   invitato durante il fine settimana garantisce un premio extra.
#

# -----> SUPPORTO PER LE STATISTICHE SOCIALI
#   Integrazione con i social (DISCORD) che permette ai giocatori di
#   ottenere la statistiche generali e specifiche...